server:
  port: 9080
  servlet:
    context-path: /

logging:
  config: classpath:log4j2.xml

#登录路径
url:
  loginUrl: https://0fd11e362210.hz-iframe-svc.simplelab.cn/goods
  adminUrl: https://0fd11e362210.hz-iframe-svc.simplelab.cn/goods/admin
  codeUrl: https://0fd11e362210.hz-iframe-svc.simplelab.cn/goods/VerifyCodeServlet?1660549377079

#读表格
testcaseexcel:
  path: src/main/resources/testcaseexcel/loginlanqiao.xlsx
  sheet1Index: 0


